[project]
name = "embroidery-workspace"
version = "0.1.0"

[[tool.mypy.overrides]]
module = "pyembroidery.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "shapely.*"
ignore_missing_imports = true

[tool.setuptools.packages.find]
exclude = ["pages*"]
