# https://docs.streamlit.io/develop/api-reference/configuration/config.toml#client
[server]
fileWatcherType = "poll"
runOnSave = true
headless = true

[client]
toolbarMode = "viewer"

[browser]
gatherUsageStats = false
